name: Pull Request on Github
on: [pull_request]
jobs:
  Pull-Request-Github:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1.3
        with: 
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "passwords"
          envkey_DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/passwords"
          directory: back-end
          file_name: .env.test
          fall_on_empty: true
      -name: Run tests backend
        run: docker compose -f docker-compose-test.yml run node npm run test   
